### ISSUE TITLE
Reporting includes wrong number of executed journeys

### ISSUE THREAD

**Issue by eleni-salamani** [mablhq/github-run-tests-action#16]
Hi,

After a successful execution of a plan with 6 journeys running on two browsers(chrome, firefox). the results include the following details

```bash
##[set-output name=plans_run;]1
##[set-output name=plans_passed;]1
##[set-output name=plans_failed;]0
**##[set-output name=journeys_run;]1
##[set-output name=journeys_passed;]1**
##[set-output name=journeys_failed;]0
```

This should be either 12 (including the total number of journeys) or 6 (the total number of journeys/browser). Maybe the output is truncated?
Please note, that the execution API reports the following result

```json
_journey_execution_metrics": {
		"total": 12,
		"passed": 12,
		"failed": 0
	},_
```

Many thanks in advance,
Elena

**Comment by gcooney** [comment]
Thanks for the report!  We'll take a look at whats happening here.
