### ISSUE TITLE
Action doesn't seem to get the right revision value

### ISSUE THREAD

**Issue by jbanulso** [mablhq/github-run-tests-action#29]
Hi,

I'm trying to use this action in our workflows to get PR checks and detailed information on runs for each commit, however I can't seem to get this work.

I get this from the logs:
```
Gathering inputs
  Using git revision [SHA]
```

However that SHA is not the last commit SHA on my PR, but rather a SHA of a "detached HEAD state", which I can confirm if I try to visit the url of that SHA in github.com, I get a warning saying "This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository".

Am I doing something fundamentally wrong? I am using the action as in the example in the README.

**Comment by gcooney** [comment]
@jbanulso Can you share the trigger for the workflow.  Are you triggering on [push] or [pull_request]?

**Comment by gcooney** [comment]
Ok, it looks like the GITHUB_SHA environment variable isn't the HEAD commit of the branch for action type pull_request: https://github.community/t/github-sha-not-the-same-as-the-triggering-commit/18286
https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#workflow_dispatch

We will work on a fix to grab the SHA of the tip commit on the branch a different way.

**Comment by gcooney** [comment]
Thanks for the report!

**Comment by jbanulso** [comment]
No problem, thank you for looking into it. And for the record, it works fine when the trigger is `on: [push]`

**Comment by gcooney** [comment]
@jbanulso This fix was released last week.  Let us know if you are still seeing issues.
