### ISSUE TITLE
Test Action Occasionally Gets Stuck

### ISSUE THREAD

**Issue by shreecodes** [mablhq/github-run-tests-action#48]
Hello, we're using `mablhq/github-run-tests-action@v1` in some of our CI/CD workflows.

Most of the time, it works great! Occasionally, maybe 1 out of 10 times, we are seeing an issue where the action hangs on `Await completion of tests`, and it thinks there is still a test plan running, even if the test plan appears to be complete in the Mabl web UI. We've seen the action get stuck indefinitely, requiring a manual cancellation, or it gets killed when Github's default 6 hour max duration for a step is exceeded.

We know we can add a timeout to the test step, but it still requires manual intervention to follow up on the real test result. We'd love to keep things automated as much as possible!

**Comment by twistedpair** [comment]
@shreecodes , thanks for reporting this issue. We've added extra timeout logic that should address cases of occasional "hanging" test runs, in [v1.11](https://github.com/mablhq/github-run-tests-action/releases/tag/v1.11).

I'm closing this as fixed for now. Please leave a comment if you see a recurrence.
