### ISSUE TITLE
Test Name is not displayed

### ISSUE THREAD

**Issue by trangpmnguyen12** [mablhq/github-run-tests-action#63]
I integrate mabl test with Github, everything is ok, except Test Name is not displayed
https://github.com/trangpmnguyen12/trangpmnguyen12.github.io/actions/runs/10040005822/job/27745140642 
<img width="959" alt="missing test name_3" src="https://github.com/user-attachments/assets/f7fb18a0-cf82-4b2c-9ac8-32aa97ef615a">
<img width="949" alt="missing test name_4" src="https://github.com/user-attachments/assets/0c824ff3-e233-40d4-91c9-b00b14d9b396">

**Comment by gcooney** [comment]
Hi @trangpmnguyen12!  Thanks for the report.  The issue was upstream in an API endpoint this action depends on and has been addressed.  Closing this ticker but feel free to re-open if you are still seeing the issue with new action executions.
